title: 2nd Ramulator & DRAM Bender Tutorial @ ISCA 2026
description: Cutting-Edge Infrastructures for Real and Future Memory System Evaluation @ ISCA 2026
baseurl: ""
url: "https://olgunataberk.github.io"

# Theme settings
# remote_theme: pages-themes/primer@v0.6.0
theme: minima
plugins:
  - jekyll-remote-theme

# Site settings
show_downloads: false
google_analytics:

# Tutorial details
workshop:
  title: "2nd Ramulator & DRAM Bender Tutorial"
  full_title: "Cutting-Edge Infrastructures for Real and Future Memory System Evaluation"
  date: "June 27th, 2026"
  location: "Raleigh, North Carolina, USA"
  venue: "Raleigh Convention Center, 500 South Salisbury Street, Raleigh, NC 27601, USA"
  conference: "ISCA 2026"
  conference_full: "International Symposium on Computer Architecture"
  livestream: "TBD"
